import ProfileimgJpeg from "../../assets/images/profileimg.jpeg";

const LatestMarketNewsData = [
    {
        id: 1,
        img: ProfileimgJpeg,
        title: "Tech Stocks Rally as Earnings Beat Expectations",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://dailynews.com",
        tags: ["New", "Popular", "High Return"],
        like: "12",
        dislike: "14",
        up: "14",
        down: "10",
    },
    {
        id: 2,
        img: ProfileimgJpeg,
        title: "Tech Stocks Rally as Earnings Beat Expectations",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://acfagh.com",
        tags: ["BBB", "PopulaAAAAr", "High Return"],
        like: "1",
        dislike: "2",
        up: "3",
        down: "4",
    },
    {
        id: 3,
        img: ProfileimgJpeg,
        title: "Tech Stocks aafgahj as Earnings Beat Expectations",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://dailynews.com",
        tags: ["AAANew", "Popular", "More", "High Return"],
        like: "12",
        dislike: "14",
        up: "14",
        down: "10",
    },
    {
        id: 4,
        img: ProfileimgJpeg,
        title: "Tech AAA Rally as Earnings Beat Expectations",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://dailynews.com",
        tags: ["New", "Popular", "High Return"],
        like: "12",
        dislike: "14",
        up: "14",
        down: "10",
    },
];

const PopularMarketNewsData = [
    {
        id: 1,
        img: ProfileimgJpeg,
        title: "A",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://dailynews.com",
        tags: ["New", "Popular", "High Return"],
        like: "12",
        dislike: "14",
        up: "14",
        down: "10",
    },
    {
        id: 2,
        img: ProfileimgJpeg,
        title: "WWW",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://acfagh.com",
        tags: ["BBB", "PopulaAAAAr", "High Return"],
        like: "1",
        dislike: "2",
        up: "3",
        down: "4",
    },
    {
        id: 3,
        img: ProfileimgJpeg,
        title: "Koorrvfstghs",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://dailynews.com",
        tags: ["AAANew", "Popular", "More", "High Return"],
        like: "12",
        dislike: "14",
        up: "14",
        down: "10",
    },
    {
        id: 4,
        img: ProfileimgJpeg,
        title: "Tech AAA Rally as Earnings Beat Expectations",
        time: "3h",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore incididunt ut laboreut labore...",
        link: "https://dailynews.com",
        tags: ["New", "Popular", "High Return"],
        like: "12",
        dislike: "14",
        up: "14",
        down: "10",
    },
];

export { LatestMarketNewsData, PopularMarketNewsData };
